FROM php:7.2-apache
RUN apt-get update
COPY . /var/www/
WORKDIR /var/www
RUN pecl install xdebug-2.7.0 && docker-php-ext-enable xdebug \
    && echo "zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20170718/xdebug.so"  \
    && echo "xdebug.remote_port=9011" >> /usr/local/etc/php/php.ini \
    && echo "xdebug.remote_enable=1" >> /usr/local/etc/php/php.ini \
    && echo 'xdebug.remote_autostart=1' >> /usr/local/etc/php/php.ini \
    && echo "xdebug.remote_host='10.0.2.15'" >> /usr/local/etc/php/php.ini \
    && echo "xdebug.idekey=sublime.xdebug" >> /usr/local/etc/php/php.ini \
    && echo "xdebug.remote_autostart=1" >> /usr/local/etc/php/php.ini \
    && echo "xdebug.remote_log=/tmp/xdebug.log" >> /usr/local/etc/php/php.ini

